### ISSUE TITLE
Please support empty context

### ISSUE THREAD

**Issue by Andries-Smit** [bartrikers/DateRangePicker#1]
When the widget is placed in a listing data view, it could be that no item is selected so the context will be empty in the function `update` 

This will cause an error at line 
https://github.com/bartrikers/DateRangePicker/blob/master/src/DateRangePicker/widget/DateRangePicker.js#L173

Recommended to check if object is available, if not clear the current value and disable the input.

**Comment by bartrikers** [comment]
Hi Andries, thanks for reporting this issue. Will fix this in the next release!

Kind regards,
Bart

**Comment by bartrikers** [comment]
Released new version where this issue is fixed
